/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGnosisSafe,
  IGnosisSafeInterface,
} from "../../../contracts/interfaces/IGnosisSafe";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signatures",
        type: "bytes",
      },
    ],
    name: "checkSignatures",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

export class IGnosisSafe__factory {
  static readonly abi = _abi;
  static createInterface(): IGnosisSafeInterface {
    return new utils.Interface(_abi) as IGnosisSafeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGnosisSafe {
    return new Contract(address, _abi, signerOrProvider) as IGnosisSafe;
  }
}
