/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  TestHandler,
  TestHandlerInterface,
} from "../../../contracts/test/TestHandler";

const _abi = [
  {
    inputs: [],
    name: "dudududu",
    outputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "manager",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061010e806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806354955e5914602d575b600080fd5b60336048565b604051603f9291906083565b60405180910390f35b6000806051605f565b6057606e565b915091509091565b6000601436033560601c905090565b600033905090565b607d8160a8565b82525050565b6000604082019050609660008301856076565b60a160208301846076565b9392505050565b600060b18260b8565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff8216905091905056fea2646970667358221220920759c34aed9194daec43b8015b04a968d35e12ab32677cde6c9fddd86a94ee64736f6c63430008010033";

type TestHandlerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestHandlerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestHandler__factory extends ContractFactory {
  constructor(...args: TestHandlerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TestHandler> {
    return super.deploy(overrides || {}) as Promise<TestHandler>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): TestHandler {
    return super.attach(address) as TestHandler;
  }
  override connect(signer: Signer): TestHandler__factory {
    return super.connect(signer) as TestHandler__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestHandlerInterface {
    return new utils.Interface(_abi) as TestHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestHandler {
    return new Contract(address, _abi, signerOrProvider) as TestHandler;
  }
}
